### ISSUE TITLE
咨询DKRL的相关细节

### ISSUE THREAD

**Issue by dingboy** [xrb92/DKRL#14]
谢同学：
  你好！
  近日看了你在表示学习领域的一系列工作，受到了很大启发。
  对于其中的DKRL模型，我有一些困惑，还望你解答下:
     1.DKRL(CNN)+TranE这种模式下，两者的权重具体是怎么取的？
     2.zeroshot这种场景下，进行实体(关系)预测时是分别用的hit@10(1)？最终的结果是(头)尾预测的平均?
     3.CBOW模型中keywords的embedding是直接通过word2vec得到的还是通过总目标函数学习得到的？
     4.论文中DKRL模型的结果是使用了总的目标函数（结构+描述）还是仅用结构向量或者仅用描述向量？

**Comment by lileilai** [comment]
> 谢同学：
> 你好！
> 近日看了你在表示学习领域的一系列工作，受到了很大启发。
> 对于其中的DKRL模型，我有一些困惑，还望你解答下:
> 1.DKRL(CNN)+TranE这种模式下，两者的权重具体是怎么取的？
> 2.zeroshot这种场景下，进行实体(关系)预测时是分别用的hit@10(1)？最终的结果是(头)尾预测的平均?
> 3.CBOW模型中keywords的embedding是直接通过word2vec得到的还是通过总目标函数学习得到的？
> 4.论文中DKRL模型的结果是使用了总的目标函数（结构+描述）还是仅用结构向量或者仅用描述向量？

同学：
你好！
请问你最终有复现出这个论文实验的结果吗？期望能交流，微信18770002143
