### ISSUE TITLE
你好，我想问一下实验结果和训练时间的问题

### ISSUE THREAD

**Issue by chehefei** [xrb92/DKRL#26]
你好，我按照代码中默认的参数（也是论文中最优参数）：
int    method = 1;  
int    n      = 100; 
int    n_1    = 100; 
int    n_w    = 100; 
double rate   = 0.001; 
double margin = 1;   
nbatches   = 100;                                  
nepoch = 1000;
线程数=16
在服务器上训练的时间非常长（需要好几天），但是最后得出的测试结果却不是很好，类似于这样
left:	7603.11	0.00044	7491.52	0.00044
right:	7668.68	0.00044	7601.83	0.00044
mid:	1261.81	0	1261.49	0
rel:/award/award_nominee/award_nominations./award/award_nomination/award_nominee 1706
left:7242.32	0	7234.8	0
right:7284.33	0.000586166	7276.77	0.000586166
mid:1345	0	1344.47	0
想问问您这是为什么，我有些困惑，因为硬件配置并没有很差，代码和数据集也都是github上的源码。
希望您能回复，万分感谢！

**Comment by zhanking321** [comment]
你好，你是用的作者的数据吗？我用他的数据要跑6、7天时间

**Comment by chehefei** [comment]
> 你好，你是用的作者的数据吗？我用他的数据要跑6、7天时间


> 你好，你是用的作者的数据吗？我用他的数据要跑6、7天时间

**Comment by chehefei** [comment]
> 你好，你是用的作者的数据吗？我用他的数据要跑6、7天时间

是的，也是跑了很久，但我后面就没有再看这方面的了
